[tool.poetry]
name = "broken-pandas"
version = "0.1.0"
description = ""
authors = ["Daniel Baker <daniel.n.baker@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
